//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
<<<<<<< HEAD
//     Runtime Version:4.0.30319.42000
=======
//     Runtime Version:4.0.30319.17929
>>>>>>> 749490da78b5864c04225b7130f4d0fd6de3e44e
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace usoSQLAdapter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
<<<<<<< HEAD
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
=======
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
>>>>>>> 749490da78b5864c04225b7130f4d0fd6de3e44e
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=E:\\1.Lab3\\WindowsForm-master\\UTN_Negoci" +
            "o.mdf;Integrated Security=True")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=UTN_Negocio;Integrated Security=True")]
>>>>>>> 749490da78b5864c04225b7130f4d0fd6de3e44e
        public string UTN_Negocio {
            get {
                return ((string)(this["UTN_Negocio"]));
            }
        }
    }
}
